import Head from 'next/head';
import { useState, useEffect } from 'react';
import { FirstTileRow } from '../components/FirstTileRow';
import { SecondTileRow } from '../components/SecondTileRow';
import { ThirdTileRow } from '../components/ThirdTileRow';
import { ForthTileRow } from '../components/ForthTileRow';
import { FifthTileRow } from '../components/FifthTileRow';
import { fiveLetterWords } from '../data/data';
// Keyboard
import Keyboard from 'react-simple-keyboard';
import 'react-simple-keyboard/build/css/index.css';
import Modal from '../components/Modal';

export default function Home({ todaysWord }) {
  const [triesEnterPress, setTriesEnterPress] = useState(0);
  const [modal, setModal] = useState(true);

  if (triesEnterPress === 5) {
    alert(`You Lost! The Words was ${todaysWord}. Press Ok to Play Again.`);
    location.reload();
    setTriesEnterPress(0);
  }

  const onKeyPress = (button) => {
    if (button === '{bksp}') {
      window.dispatchEvent(new KeyboardEvent('keydown', { key: 'Backspace' }));
    } else if (button === '{enter}') {
      window.dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter' }));
    } else {
      window.dispatchEvent(new KeyboardEvent('keydown', { key: button }));
    }
  };

  return (
    <div>
      <Head>
        <title>Wordle Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Modal setModal={setModal} modal={modal} />
      <main className=" pb-8">
        <nav className="flex justify-center py-3 border-b-2 border-gray-700/50">
          <h1 className="text-white font-bold text-2xl md:text-3xl cursor-pointer">
            Wordle Clone
          </h1>
        </nav>
        <div className="flex flex-col space-y-3 pt-5 md:pt-20 lg:pt-28 items-center">
          <FirstTileRow
            todaysWord={todaysWord}
            triesEnterPress={triesEnterPress}
            setTriesEnterPress={setTriesEnterPress}
          />
          <SecondTileRow
            todaysWord={todaysWord}
            triesEnterPress={triesEnterPress}
            setTriesEnterPress={setTriesEnterPress}
          />
          <ThirdTileRow
            todaysWord={todaysWord}
            triesEnterPress={triesEnterPress}
            setTriesEnterPress={setTriesEnterPress}
          />
          <ForthTileRow
            todaysWord={todaysWord}
            triesEnterPress={triesEnterPress}
            setTriesEnterPress={setTriesEnterPress}
          />
          <FifthTileRow
            todaysWord={todaysWord}
            triesEnterPress={triesEnterPress}
            setTriesEnterPress={setTriesEnterPress}
          />
        </div>
        <div className=" relative max-h-70 w-11/12 py-2 mx-auto flex lg:hidden z-40">
          <Keyboard
            onKeyPress={onKeyPress}
            theme={'hg-theme-default myTheme1'}
            layout={{
              default: [
                'q w e r t {bksp}',
                'y u i o p',
                'a s d f g',
                'h j k l z x',
                'c v b n m {enter}',
              ],
            }}
          />
        </div>
      </main>
      <footer className="flex justify-center items-center">
        <h1 className=" text-gray-400 text-sm lg:text-lg">
          Developed by{' '}
          <a
            href="https://hmk360.netlify.app/"
            target="_blank"
            className="hover:underline"
            rel="noreferrer"
          >
            Rumon
          </a>
        </h1>
      </footer>
    </div>
  );
}
export async function getServerSideProps(context) {
  const random = Math.floor(Math.random() * fiveLetterWords.length);
  let todaysWord = fiveLetterWords[random];
  return {
    props: {
      todaysWord,
    }, // will be passed to the page component as props
  };
}
